# NumPy

**NumPy 2D array**

In [1]:
import numpy as np
l=[[1,2,3],[4,5,6],[7,8,9]]
b=np.array(l,dtype=int)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**NumPy 0s and 1s**

In [3]:
#Create an integer array of size 10, where all the values should be 0 but the fifth value should be 1.
import numpy as np
arr = np.zeros(10, dtype=int)
arr[4] = 1
print(*arr)

0 0 0 0 1 0 0 0 0 0


**NumPy Inclusive**

In [4]:
#Create an array with values ranging consecutively from 9 to 49 (both inclusive).
#Print the Numpy array.
import numpy as np
b = np.arange(9,50)
print(*b)

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49


**Identity Matrix**

In [5]:
#Create a matrix having diagonal elements as 1 and all other elements as 0 of size (5, 6).
import numpy as np
b = np.eye(5,6, dtype = int)
print(b)

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]]


**Cut the Rope**

In [6]:
#You are given a rope of length 5m. Cut the rope into 9 parts such that each part is of equal length
import numpy as np
arr = np.linspace(0,5,10)
for i in range(1, len(arr)-1) :
    print(round(arr[i],2))

0.56
1.11
1.67
2.22
2.78
3.33
3.89
4.44


**Print Elements**

In [7]:
#Given a 2D integer array size (4, 5) with name input_?
import numpy as np
input_ = np.arange(1,21,1)
input_ = input_.reshape(4,5)
print(*input_[2,:3])

print(*input_[1:4,3])

c = input_[2:4,:5]
print(*c[0],end=' ')
print(*c[1],end=' ')
print()

c = input_[1:3,1:3]
print(*c[0],end=' ')
print(*c[1],end=' ')

11 12 13
9 14 19
11 12 13 14 15 16 17 18 19 20 
7 8 12 13 

**Non-Zero elements**

In [8]:
#Find indices of non-zero elements from the array [1,2,0,0,4,0] ?
#Print the index of non-zero elements.
import numpy as np
arr = np.array([1,2,0,0,4,0])
ind = np.where(arr != 0)
print(*ind[0])

0 1 4


**Multiples of 3**

In [9]:
import numpy as np
arr = np.arange(1,20,2)
ind = np.where(arr%3 == 0)
print(*ind[0])

1 4 7


**Odd elements**

In [10]:
#Given an integer array of size 10. Replace the odd number in numpy array with -1 ?
import numpy as np
arr = np.arange(1,11)
arr[arr % 2 != 0] = -1
print(*arr)

-1 2 -1 4 -1 6 -1 8 -1 10


**Replace Max**

In [11]:
#Given an integer array of size 9 and replace the first occurrence of maximum value by 0?
import numpy as np
arr = np.array([11, 2, 13, 4, 15, 6, 27, 8, 19])
arr[arr.argmax()] = 0
for i in arr :
    print(i)

11
2
13
4
15
6
0
8
19


**Negate Elements**

In [12]:
#Given a 1D array, negate all elements which are between 3 and 8 (both inclusive)?
import numpy as np
arr = np.arange(1,11)
arr[2:8] = np.multiply(arr[2:8],-1)
for i in arr:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


**Height**

In [13]:
#Given age and height of 20 students in two different numpy arrays with name age and height (in cms). 
#Print the age of those students whose height is above 155 cm.
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
ind = np.where(height > 155)
for i in range(len(ind[0])):
    print(age[ind[0][i]], height[ind[0][i]])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


**Sort by column**

In [14]:
#Sort a given 2D array of shape (4, 5) by 2nd column (i.e. column at index 1) in ascending order.
#That means, we should re-arrange complete row based on 2nd columns' values.
import numpy as np
a = np.array([[21, 20, 19, 18, 17], [16, 15, 14, 13, 12], [11, 10,  9,  8,  7], [ 6,  5,  4,  3,  2]])
a = a[a[:, 0].argsort()]
print(a)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


**Killed in USA**


In [ ]:
#Find value of killed column only where country == ‘United States’?
#Print 0 in place of missing values.
#Print count of Killed as integer value.
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)

    killed = []
    country = []
    for row in data:
        killed.append(row['Killed'])
        country.append(row['Country'])

    np_killed = np.array(killed)
    np_country = np.array(country)
    
    np_killed[np_killed == ''] = '0.0'
    np_killed = np.array(np_killed,dtype=float)
    
    np_country = np.array(country)
    bool_arr = np_country=="United States"
    ans = np_killed[bool_arr]   
    for i in ans:
        print(int(i))

**Total Killed in USA**

In [ ]:
import numpy as np
import csv

with open('terrorismData.csv',encoding="utf8") as file_obj :
    data = csv.DictReader(file_obj,skipinitialspace=True)

    killed = []
    country = []
    for row in data:
        killed.append(row['Killed'])
        country.append(row['Country'])

    np_killed = np.array(killed)
    np_country = np.array(country)
    
    np_killed[np_killed=='']= '0.0'
    np_killed = np.array(np_killed,dtype=float)
    
    np_country = np.array(country)
    bool_arr = np_country == "United States"
    ans = np_killed[bool_arr]
    
    print(int(np.sum(ans)))
    
    
# Output :  3771 